[settings]
animate = true

focus_follows_mouse = true
mouse_follows_focus = true
mouse_hides_on_focus = true

auto_focus_blacklist = []

run_on_start = []

hot_reload = true

[settings.layout]
mode = "traditional"

[settings.layout.stack]
stack_offset = 40.0

default_orientation = "perpendicular"

[settings.layout.gaps]

[settings.layout.gaps.outer]
top = 12
left = 12
bottom = 12
right = 12

[settings.layout.gaps.inner]
horizontal = 12
vertical = 12

[settings.ui.menu_bar]
enabled = true
mode = "active"
display_style = "label"
active_label = "name"

[settings.ui.stack_line]
enabled = false

[settings.ui.mission_control]
enabled = true
fade_enabled = false
fade_duration_ms = 180.0

[settings.gestures]
enabled = true
swipe_vertical_tolerance = 0.4
skip_empty = true
fingers = 4
distance_pct = 0.08
haptics_enabled = true
haptic_pattern = "level_change"

[settings.window_snapping]
drag_swap_fraction = 0.3

[virtual_workspaces]
enabled = true
default_workspace_count = 10
auto_assign_windows = true
preserve_focus_per_workspace = true
workspace_auto_back_and_forth = false

[modifier_combinations]
focus = "Alt"
move = "Alt + Shift"
group = "Ctrl + Alt"

[keys]
"Alt + Z" = "toggle_space_activated"

"Alt + Comma" = "toggle_stack"
"Alt + Slash" = "toggle_orientation"

"focus + H" = { move_focus = "left" }
"focus + J" = { move_focus = "down" }
"focus + K" = { move_focus = "up" }
"focus + L" = { move_focus = "right" }

"move + H" = { move_node = "left" }
"move + J" = { move_node = "down" }
"move + K" = { move_node = "up" }
"move + L" = { move_node = "right" }

"group + U" = "unjoin_windows"
"group + H" = { join_window = "left" }
"group + L" = { join_window = "right" }
"group + K" = { join_window = "up" }
"group + J" = { join_window = "down" }

"Alt + Tab" = "switch_to_last_workspace"
# "Alt + Shift + Tab" should move the current space between monitors

"Alt + Shift + Equal" = "resize_window_grow"
"Alt + Shift + Minus" = "resize_window_shrink"

"focus + 0" = { switch_to_workspace = 0 }
"focus + 1" = { switch_to_workspace = 1 }
"focus + 2" = { switch_to_workspace = 2 }
"focus + 3" = { switch_to_workspace = 3 }
"focus + 4" = { switch_to_workspace = 4 }
"focus + 5" = { switch_to_workspace = 5 }
"focus + 6" = { switch_to_workspace = 6 }
"focus + 7" = { switch_to_workspace = 7 }
"focus + 8" = { switch_to_workspace = 8 }
"focus + 9" = { switch_to_workspace = 9 }

"move + 0" = { move_window_to_workspace = 0 }
"move + 1" = { move_window_to_workspace = 1 }
"move + 2" = { move_window_to_workspace = 2 }
"move + 3" = { move_window_to_workspace = 3 }
"move + 4" = { move_window_to_workspace = 4 }
"move + 5" = { move_window_to_workspace = 5 }
"move + 6" = { move_window_to_workspace = 6 }
"move + 7" = { move_window_to_workspace = 7 }
"move + 8" = { move_window_to_workspace = 8 }
"move + 9" = { move_window_to_workspace = 9 }

"Alt + Shift + Space" = "toggle_window_floating"
"Alt + F" = "toggle_fullscreen"
"Alt + Shift + F" = "toggle_fullscreen_within_gaps"

"Alt + Space" = "show_mission_control_all"

"Alt + Shift + D" = "debug"

"Alt + Ctrl + S" = "serialize"
"Alt + Ctrl + Q" = "save_and_exit"
